### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by sarmadhamdani02** [sarmadhamdani02/WebGames#10]
Add dark mode to the main web page of the project.

**Comment by khushal786** [comment]
Hey can I see the project so I can work on it

**Comment by sarmadhamdani02** [comment]
This issue has not been assigned to anyone, I can surely assign this to you :)

**Comment by sarmadhamdani02** [comment]
@MRodriguez-M, I am thinking about some dark shade of blue as the background color for the webpage 🤔 but do it as you want.

**Comment by SameerJS6** [comment]
Hey, is this being worked on? And if not, can it be assigned to me? Also, do we have to add a dark theme only to the [Main Page](https://sarmadhamdani02.github.io/webGames/) or to any of the included games as well?

This One? Right?
![Screenshot (103)](https://github.com/sarmadhamdani02/webGames/assets/110624457/6ac9936a-542e-4760-83fb-c903d687ec7c)

**Comment by sarmadhamdani02** [comment]
> Hey, is this being worked on? And if not, can it be assigned to me? Also, do we have to add a dark theme only to the [Main Page](https://sarmadhamdani02.github.io/webGames/) or to any of the included games as well?
> 
> This One? Right?
> ![Screenshot (103)](https://github.com/sarmadhamdani02/webGames/assets/110624457/6ac9936a-542e-4760-83fb-c903d687ec7c)
> 

Hi @SameerJS6 👋
This issue has been assigned to @MRodriguez-M

**Comment by SameerJS6** [comment]
> > Hey, is this being worked on? And if not, can it be assigned to me? Also, do we have to add a dark theme only to the [Main Page](https://sarmadhamdani02.github.io/webGames/) or to any of the included games as well?
> > This One? Right?
> > ![Screenshot (103)](https://user-images.githubusercontent.com/110624457/261291570-6ac9936a-542e-4760-83fb-c903d687ec7c.png)
> 
> Hi @SameerJS6 👋 This issue has been assigned to @MRodriguez-M

Ok

**Comment by MRodriguez-M** [comment]
> @MRodriguez-M, I am thinking about some dark shade of blue as the background color for the webpage 🤔 but do it as you want.

Hey @sarmadhamdani02, that's interesting, I will play with a dark blue background and see how that looks. I was going to go with a dark gray, but I think blue will make the design more appealing
