### ISSUE TITLE
Add themes to the Tic Tac Toe game

### ISSUE THREAD

**Issue by sarmadhamdani02** [sarmadhamdani02/webGames#11]
It would greatly enhance the gaming experience to introduce various themes to the game. To achieve this, we can implement multiple color schemes for both the background and the game panel (identified by the 'game-container' class in the HTML) on the main game screen (identified by the 'main' class).

One of the possible solutions can be creating arrays of colors for the background as well as the game panel ("game-container" class in HTML)  in a Javascript file and using Math.random function to get different index numbers each time and so having different background colors each time game starts. 

Make sure the colors don't spoil the overall theme of the game.

**Comment by SandipGyawali** [comment]
I can work on this issue. @sarmadhamdani02 can you assign me this issue?

**Comment by sarmadhamdani02** [comment]
Sure @SandipGyawali 🙌
