### ISSUE TITLE
Fix README.md file

### ISSUE THREAD

**Issue by sarmadhamdani02** [sarmadhamdani02/WebGames#22]
In the README.md file, there is a typo error in the last line.
Also, add the webpage icon (from `assets\page_icon.png`) on the top of the file just below the main heading.

**Comment by sarmadhamdani02** [comment]
The typo has now been fixed in pull request #24. 
Now, we only need to add the webpage icon image at the top, as specified above.

**Comment by avinashji1302** [comment]
I am  not getting this issue , Please provide some more context .....I want fix it

**Comment by sarmadhamdani02** [comment]
So, there is an image named page_icon.png in the assets folder. All you have to do is to add that image on the top of the README.md file right after the main title (first heading) of the README.

**Comment by sarmadhamdani02** [comment]
> So, there is an image named page_icon.png in the assets folder. All you have to do is to add that image on the top of the README.md file right after the main title (first heading) of the README.

SO in this way we will have our webpage icon on the top of the readme file. Got it?

**Comment by avinashji1302** [comment]
> > So, there is an image named page_icon.png in the assets folder. All you have to do is to add that image on the top of the README.md file right after the main title (first heading) of the README.
> 
> SO in this way we will have our webpage icon on the top of the readme file. Got it?

Please check I tried it
