### ISSUE TITLE
Tic-tac-toe: `win-screen` bug

### ISSUE THREAD

**Issue by sarmadhamdani02** [sarmadhamdani02/WebGames#27]
So there is a bug in the game over screen that appears when game overs (with HTML class name `win-screen`) in the Tic-Tac-Toe game.

The bug is: when the game overs for the first time there is no animation in the game over screen message instead it just suddenly appears on the screen. After the first game when we restart the game, the bug disappears and animation can be seen with every other message.

**Comment by Camarota-234** [comment]
I can help with this one, please assign me this one

**Comment by Camarota-234** [comment]
#72 already fixed it
