### ISSUE TITLE
The Bubble Game: Bug 

### ISSUE THREAD

**Issue by sarmadhamdani02** [sarmadhamdani02/WebGames#33]
There is a bug in the bubble game. When we click the div behind the bubble, the event also runs and it decreases the points. 🫤

**Comment by MRodriguez-M** [comment]
Hi, i'll be taking a look at both the bubble game bugs (this one and issue #34). If you would prefer we only take a look at one issue at a time, i'll start with just this one

**Comment by sarmadhamdani02** [comment]
> That will be awesome @MRodriguez-M 👍
> 
> Let me assign both of these issues to you.
> 
> Thanks.

Hey @MRodriguez-M  could you please comment on the other issue so that I will be able to assigned that yo you as well.

**Comment by MRodriguez-M** [comment]
> > That will be awesome @MRodriguez-M 👍
> > Let me assign both of these issues to you.
> > Thanks.
> 
> Hey @MRodriguez-M could you please comment on the other issue so that I will be able to assigned that yo you as well.

No problem, will go leave a comment
