### ISSUE TITLE
The Bubble Game: change `.main-instruction` background color.

### ISSUE THREAD

**Issue by sarmadhamdani02** [sarmadhamdani02/WebGames#39]
The color of the `.main-instruction` (instructions that appear on the start game screen) of Bubble Game has the same background color as the main screen div behind it just with more background blur. Change the `.main-instruction` background color to something more appealing and readable to the user.

**Comment by Phil94comp** [comment]
I just submitted a pull request. Please let me know if you like the changes.

**Comment by Phil94comp** [comment]
I just updated the code to the specifications you want. Please let me know if this meets the requirement.
