### ISSUE TITLE
Dev Quiz: game-over screen bug.

### ISSUE THREAD

**Issue by sarmadhamdani02** [sarmadhamdani02/WebGames#48]
So, recently a new game [Dev Quiz](https://sarmadhamdani02.github.io/WebGames/DevQuiz/index.html) has been added.
However, there is a bug: on the `game-end-panel` which is the div for game over screen, it shows score and percentage which is not being shown correctly.

**Comment by sarmadhamdani02** [comment]
Sure @miraclemoses. 🙌
But If I am not wrong this issue was automatically resolved while solving other issues. Just recheck whether this issue still exists or not.

**Comment by miraclemoses** [comment]
Check my recent pull request, though this was handled.

**Comment by miraclemoses** [comment]
This request should be closed
