### ISSUE TITLE
Dev Game: bug 

### ISSUE THREAD

**Issue by sarmadhamdani02** [sarmadhamdani02/WebGames#50]
In the `checkAnswer()` function, the intention is to add the CSS class `.right-option` to the correct answer and if the user has selected the wrong option `.wrong-option`  will be added to the option. However, it seems that this behavior isn't functioning as intended.  

If the classes are added properly, the right answer will have a border color and font color of `limegreen` and for the wrong answer, it is `crimson`.

**Comment by MRodriguez-M** [comment]
Hi, has this been resolved yet? I want to take a look at it if not

**Comment by sarmadhamdani02** [comment]
Sure @MRodriguez-M 🙏
