### ISSUE TITLE
Add restart game button at the game-over screen of the game.

### ISSUE THREAD

**Issue by sarmadhamdani02** [sarmadhamdani02/WebGames#51]
At the game over screen, add a Restart Game Button. This button would serve the purpose of restarting the game when clicked.

**Comment by TayzCodes** [comment]
Can you assign this to me? @sarmadhamdani02

**Comment by treblig-punisher** [comment]
Hey Can I be assigned this?

**Comment by sarmadhamdani02** [comment]
Apologies, the task is already completed.
