### ISSUE TITLE
main website responsiveness issue

### ISSUE THREAD

**Issue by sarmadhamdani02** [sarmadhamdani02/WebGames#58]
There is a problem with the responsiveness of the main website as shown in the screenshot below,

![image](https://github.com/sarmadhamdani02/WebGames/assets/111639663/b11562a5-d8c3-4fb9-9c42-d332167151d0)

**Comment by avinashji1302** [comment]
please assign me this

**Comment by sarmadhamdani02** [comment]
Hello @avinashji1302 👋👋,

I hope you're doing well! I wanted to let you know that the issue you has already been assigned to @lefty93.

**Comment by avinashji1302** [comment]
> Hello @avinashji1302 👋👋,
> 
> I hope you're doing well! I wanted to let you know that @lefty93 is already working on it.

No Problem , Next time
