### ISSUE TITLE
Dev Quiz: responsiveness issue.

### ISSUE THREAD

**Issue by sarmadhamdani02** [sarmadhamdani02/WebGames#61]
Games menu and end screen are responsive but there are still some problems with the main game screen.

Firstly, the game options sometimes get out of the screen so effects the user experience.

Secondly, increase the score font-size a bit so it will be more visible. 

![Screenshot_20230827-132137.png](https://github.com/sarmadhamdani02/WebGames/assets/111639663/1ab5f503-7804-4bb4-8c92-a08e6c2e07f3)

**Comment by avinashji1302** [comment]
Please assign me this

**Comment by sarmadhamdani02** [comment]
Sure @avinashji1302 🙌

**Comment by sarmadhamdani02** [comment]
Sure @avinashji1302 🙌
