### ISSUE TITLE
Tic Tac Toe game bug

### ISSUE THREAD

**Issue by sarmadhamdani02** [sarmadhamdani02/WebGames#64]
When playing on mobile and game draws instead of "Game Drawn" message following message shows.

![Screenshot_20230827-162456.png](https://github.com/sarmadhamdani02/WebGames/assets/111639663/c2f0c262-a1fd-440a-af42-95957843429f)

**Comment by Camarota-234** [comment]
Please assign me this one

**Comment by sarmadhamdani02** [comment]
Sure @Camarota-234 🙌
