### ISSUE TITLE
add responsiveness to the bubble game

### ISSUE THREAD

**Issue by sarmadhamdani02** [sarmadhamdani02/WebGames#7]

**Comment by kash5811** [comment]
can you assign this task to me?

**Comment by sarmadhamdani02** [comment]
Sure, @kash5811  🙌

**Comment by sarmadhamdani02** [comment]
@kash5811,

Could you please make changes to the instruction div of the bubble game on the start screen also? Currently, the color of the instruction div is the same as the background, which doesn't look very appealing. Could you either change it to a white color with a glass-like effect or apply a different style that aligns with the website's theme?
By the way, the actual color of the div is white but it is only being shown white in Mozilla Firefox but not others. Maybe it is some compatibility issue 🤔

**Comment by sarmadhamdani02** [comment]
Update: No need to worry about the Instruction div, as this issue has been resolved. Just focus on the responsivenss 🙂

**Comment by kash5811** [comment]
sure I'll do the responsive part

**Comment by kash5811** [comment]
can you check my pull request
