### ISSUE TITLE
Dev Quiz: Bug 

### ISSUE THREAD

**Issue by sarmadhamdani02** [sarmadhamdani02/WebGames#75]
Hi there! 👋

### Problem:
There is an issue in the **Dev Quiz** game. The problem is that when you click on the option, the right option changes its border and font color to lime green and if the player has chosen the wrong answer that selected option will be changed to border and font color Crimson.
The problem here is that sometimes the option becomes less visible due to the background theme. For example, there is a theme color of `#148f3f`, when text becomes lime green on the top of it, it becomes less visible.

### Possible Solution:
One thing we can do is just to make the border a bit wider and add some weight to the text in the option. But, I do not think it will completely solve the problem. According to my opinion, the best possible solution for this problem is that we can add some when the user clicks any option, instead of changing the border and font color of that option we can change the background color of that option and keep the font color the same as white. Adding some weight to the text of the option will also be not a bad idea. I hope this can solve the issue. You can check the classes `.right-option` and `.wrong-option` in CSS.

**Comment by NereidaRondon** [comment]
Working on this issue... ![bitmoji](https://sdk.bitmoji.com/render/panel/2196307c-2ceb-46f8-8bf4-4c3e3f34f93e-e351c6a3-28be-4ea8-ac7b-9d97907df95f-v1.png?transparent=1&palette=1&width=246)
