### ISSUE TITLE
main website responsiveness issue

### ISSUE THREAD

**Issue by sarmadhamdani02** [sarmadhamdani02/WebGames#77]
Hi there 👋

### Problem:

The nav bar of the main [webpage](https://sarmadhamdani02.github.io/WebGames/) is not fully visible for some reasons. Have a look at the screenshot below,

![image](https://github.com/sarmadhamdani02/WebGames/assets/111639663/c0922964-f938-4943-9aee-da5bb6a8ee3e)

![image](https://github.com/sarmadhamdani02/WebGames/assets/111639663/1b800e35-5ce3-4efe-914a-7c73474e1c28)

### How it should be:

All the elements of the navbar should be visible on every device ( i.e Computer screens, for mobile side menu)

**Comment by ayushichoudhary-19** [comment]
Please assign it to me.

**Comment by ayushichoudhary-19** [comment]
Working on it!
