### ISSUE TITLE
Another answer choice is incorrect for Dev Quiz

### ISSUE THREAD

**Issue by NereidaRondon** [sarmadhamdani02/WebGames#80]
QUESTION INDEX 5:
"What does CSS stand for?",

ANSWER CHOICES INDEX 5:

["Colorful Style Sheets", "Creative Style Sheets", "Cascading Style Sheets", "Computer Style Sheets"],

## PROBLEM:

ANSWER KEY ARRAY:
const key = [3, 1, 0, 3, 2, 0, 1, 3, 1, 2, 0, 0, 2, 0, 1, 0, 3, 0, 3, 2];

## How to fix it:

key[5] should be 2, not 0.

**Comment by sarmadhamdani02** [comment]
Thanks, @NereidaRondon  for figuring that out 🙏
