### ISSUE TITLE
Dev Quiz Bug: End screen percentage issue.

### ISSUE THREAD

**Issue by sarmadhamdani02** [sarmadhamdani02/WebGames#88]
Hi there! 👋

There is an issue when the game ends in the Dev Quiz game. The problem is that when the game ends there is a percentage shown to tell players their scores. That percentage is in float. So, it appears in point. All we have to fo is to convert that to int.

**Comment by PentW0lf** [comment]
i wanna work on it !

**Comment by nishantdub37** [comment]
@sarmadhamdani02 can u assign this to me?

**Comment by sarmadhamdani02** [comment]
Sure 🙌

**Comment by sarmadhamdani02** [comment]
> i wanna work on it !

Sure 😊

**Comment by PentW0lf** [comment]
your issue to convert float result into int, right?

for example: if i got 92.23345345324% then it would be appear like 92%

**Comment by sarmadhamdani02** [comment]
> your issue to convert float result into int, right?
> 
> for example: if i got 92.23345345324% then it would be appear like 92%

Yes, exactly
