### ISSUE TITLE
Adding different programming language for quiz

### ISSUE THREAD

**Issue by janetjoseph02** [sarmadhamdani02/WebGames#95]
I was solving the Dev Quiz questions but there was no end option to end the quiz, so I would like to add that feature. 
Also, it would be great if there was an option to select from multiple programming languages, so that users can choose which language they want to try.
I think the GUI can also be improved.
I would be glad to work on these issues, so it would be great if you could assign me for this issue.
Thanks,
Regards.

**Comment by sarmadhamdani02** [comment]
Sure, let me assign this to you. 👍

**Comment by janetjoseph02** [comment]
Thank you!!
